/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class Menu_BDatar extends javax.swing.JFrame {

    /**
     * Creates new form Menu_BDatar
     */
    public Menu_BDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RBPersegi = new javax.swing.JRadioButton();
        RBLingkaran = new javax.swing.JRadioButton();
        RBTrapesium = new javax.swing.JRadioButton();
        RBPersegiPanjang = new javax.swing.JRadioButton();
        RBJajarGenjang = new javax.swing.JRadioButton();
        RBLayangLayang = new javax.swing.JRadioButton();
        RBSegitiga = new javax.swing.JRadioButton();
        RBBelahKetupat = new javax.swing.JRadioButton();
        Pilih = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bangun Datar");

        jLabel2.setText("Pilih Bangun Datar :");

        RBPersegi.setText("Persegi");

        RBLingkaran.setText("Lingkaran");

        RBTrapesium.setText("Trapesium");

        RBPersegiPanjang.setText("Persegi Panjang");

        RBJajarGenjang.setText("Jajar Genjang");

        RBLayangLayang.setText("Layang-layang");

        RBSegitiga.setText("Segitiga");

        RBBelahKetupat.setText("Belah Ketupat");

        Pilih.setText("Pilih");
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBPersegiPanjang)
                            .addComponent(Pilih)
                            .addComponent(jLabel2)
                            .addComponent(RBTrapesium)
                            .addComponent(RBLingkaran)
                            .addComponent(RBPersegi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBJajarGenjang)
                            .addComponent(RBLayangLayang)
                            .addComponent(RBSegitiga)
                            .addComponent(Keluar)
                            .addComponent(RBBelahKetupat))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBPersegi)
                    .addComponent(RBJajarGenjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBLingkaran)
                    .addComponent(RBLayangLayang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBTrapesium)
                    .addComponent(RBSegitiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBPersegiPanjang)
                    .addComponent(RBBelahKetupat))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pilih)
                    .addComponent(Keluar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        // TODO add your handling code here:
        if(RBPersegi.isSelected()){
            Persegi a = new Persegi();
            a.setVisible(true);
            this.dispose();
        }else if(RBLingkaran.isSelected()){
            Lingkaran b = new Lingkaran();
            b.setVisible(true);
            this.dispose();
        }else if(RBTrapesium.isSelected()){
            Trapesium c = new Trapesium();
            c.setVisible(true);
            this.dispose();
        }else if(RBPersegiPanjang.isSelected()){
            Persegi_Panjang d = new Persegi_Panjang();
            d.setVisible(true);
            this.dispose();
        }else if(RBJajarGenjang.isSelected()){
            Jajar_Genjang e = new Jajar_Genjang();
            e.setVisible(true);
            this.dispose();
        }else if(RBLayangLayang.isSelected()){
            Layang_layang f = new Layang_layang();
            f.setVisible(true);
            this.dispose();
        }else if(RBSegitiga.isSelected()){
            Segitiga g = new Segitiga();
            g.setVisible(true);
            this.dispose();
        }else if(RBBelahKetupat.isSelected()){
            Belah_Ketupat h = new Belah_Ketupat();
            h.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_PilihActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        Menu_Utama a = new Menu_Utama();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_BDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_BDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_BDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_BDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_BDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Pilih;
    private javax.swing.JRadioButton RBBelahKetupat;
    private javax.swing.JRadioButton RBJajarGenjang;
    private javax.swing.JRadioButton RBLayangLayang;
    private javax.swing.JRadioButton RBLingkaran;
    private javax.swing.JRadioButton RBPersegi;
    private javax.swing.JRadioButton RBPersegiPanjang;
    private javax.swing.JRadioButton RBSegitiga;
    private javax.swing.JRadioButton RBTrapesium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
